name: Build & Test with Coverage

on:
  push:
    branches: main
  # pull_request:
  #   branches: main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Grant execute permissions for Gradle
        run: chmod +x gradlew

      - name: Show Gradle & Java versions
        run: |
          java -version
          ./gradlew --version

      # Run unit tests (JUnit 5) and generate JaCoCo report
      - name: Clean, Test, and generate JaCoCo report
        run: ./gradlew clean build

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: ./gradlew sonarqube
